apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sangayapp
  namespace: sangay
spec:
  project: default
  source:
    repoURL: https://github.com/sangayp607/argo.git
    targetRevision: master
    path: . 
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
